apiVersion: v1
kind: Service
metadata:
  name: fbk-api-service
  labels:
    app: fbk-api-app
spec:
  selector:
    app: fbk-api-app

  ports:
    - port: 8080
      targetPort: 8080

  type: LoadBalancer
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: fbk-api-app-vpa
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: fbk-api-deployment
  updatePolicy:
    updateMode: Auto
  resourcePolicy:
    containerPolicies:
      - containerName: '*'
        minAllowed:
          cpu: 200m
          memory: 300Mi
        maxAllowed:
          cpu: 600m  # Adjust maxAllowed as necessary
          memory: 700Mi  # Adjust maxAllowed as necessary
        controlledResources: ["cpu", "memory"]